CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "image" varchar NOT NULL,
  "category" varchar NOT NULL,
  "description" text,
  "rating" int NOT NULL,
  "num_reviews" int NOT NULL DEFAULT 0,
  "price" decimal(10,2) NOT NULL,
  "count_in_stock" int NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "payment_method" varchar NOT NULL,
  "tax_price" decimal(10,2) NOT NULL,
  "shipping_price" decimal(10,2) NOT NULL,
  "total_price" decimal(10,2) NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "name" varchar NOT NULL,
  "quantity" varchar NOT NULL,
  "image" varchar NOT NULL,
  "price" int NOT NULL
);

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");
